### PR TITLE
Multiple TS Changes and Improvements

### PR DESCRIPTION
**Pull request by YourWishes**
Refer to https://github.com/MONEI/Shopify-api-node/pull/289
Also see #288 

Also, is there a preferred prettier config? I went with `--single-quote --trailing-comma es5`, although it's done some aesthetic damage to my WebhookMap which could be a tad confusing to glance at, thoughts?

### Pull Request Fixes
Fixed commit title to omit trailing period
Ran through prettier to correct semicolon and comma inconsistencies.

### Definition Changes
Added missing property id to ICarrierService
Added Interface for ICart, ICartLineItem and IDeletedItem
Added WebhookType map, e.g. WebhookType<'products/create'> will yeild IProduct
Added various types for shipping carrier callbacks.

### CODE REVIEW

**Comment by lpinca** [comment]
No trailing commas please. Single quote is ok and consistent with current style.

**Comment by YourWishes** [comment]
> 
> 
> No trailing commas please. Single quote is ok and consistent with current style.

alright thanks for clearing up, I ran the defintions through prettier with the updated config, no changes to commit though.

**Comment by lpinca** [comment]
Rubber stamp LGTM. Are there breaking changes? I mean, do these types work with TypeScript < 3? Is there a chance that this will break people build? (I don't use TypeScript)

**Comment by YourWishes** [comment]
The map for the webhooks uses conditional types, [according to the docs](https://www.typescriptlang.org/docs/handbook/advanced-types.html#conditional-types) these were introduced in TS 2.8.x.

Reverting back to version 2.0.10 shows that it will still compile without errors when not being used, the only time an error will be thrown is when attempting to use the new maps in a format that is unexpected.

### TS 2.0.10
```
type T = Shopify.WebhookType<'products/create'>;
let x = request.get() as T;//T is type of 'products/create' not the expected IProduct
x.id;//Will result in an error since TS thinks x is a string
```

### TS 2.8.x+
```
type T = Shopify.WebhookType<'products/create'>;
let x = request.get() as T;//T is type of IProduct
x.id;//Works without error.
```

**Comment by lpinca** [comment]
Thank you.

**Pull request merged**
