### PR TITLE
Adding clearer Shopify object instantiation error messages

### PR DESCRIPTION
**Pull request by tomgs**
Because I'm stupid and misread the property name in https://github.com/MONEI/Shopify-api-node/issues/378, adding error handling so it doesn't happen to anyone else.

### CODE REVIEW

**Comment by tomgs** [comment]
Two notes:

1. No full coverage as `coveralls` mentioned above.
2. `npm run lint -- --fix` does not work, which will fail lint on the build.

**Comment by lpinca** [comment]
Do we really need this level of details for 2/3 required options :(?

**Comment by tomgs** [comment]
If it blocked me, it might block other people as well. Also, it's the entrypoint to the module - why not make it smoother?

**Comment by tomgs** [comment]
@lpinca Should I close and just use my fork instead?

**Comment by lpinca** [comment]
I would prefer to keep it as is. In my opinion this is too verbose and not really needed for just 3 options.

**Comment by tomgs** [comment]
Fair enough - hope I could offer some value elsewhere in the library.
And again, thanks for writing this!

**Pull request closed without merging**
