### PR TITLE
[typings] applicationCharge.activate params arg is optional

### PR DESCRIPTION
**Pull request by dhritzkiv**

### CODE REVIEW

**Comment by lpinca** [comment]
The [example](https://help.shopify.com/api/reference/applicationcharge#activate) has a body but if it works without it, can you also update the readme? Thank you.

**Comment by lpinca** [comment]
I will merge this tomorrow but I'd prefer to wait a bit before cutting a new release in order to accumulate more fixes. Does this issue prevent compilation from completing?

**Comment by dhritzkiv** [comment]
That's cool.

> Does this issue prevent compilation from completing?

Not for me

**Comment by lpinca** [comment]
Thank you.

**Pull request merged**
