### PR TITLE
[ts] Improve constructor option definitions

### PR DESCRIPTION
**Pull request by dhritzkiv**
- marks timeout as an optional field
- use and extend a common interface for both config interfaces

### CODE REVIEW

**Comment by lpinca** [comment]
cc: @buggy

**Comment by buggy** [comment]
@dhritzkiv Can you remove the second commit from this PR (the one that creates ICommonShopifyConfig)? There are only 2 common fields and having this makes the code less readable.

Also, can you rename the PR to start with [ts] so it's easy to track all of the TypeScript commits.

**Comment by dhritzkiv** [comment]
Removed the second commit

**Comment by lpinca** [comment]
Thank you.

**Pull request merged**
