### PR TITLE
[Improvement]: implementation of delay function without setTimeout

### PR DESCRIPTION
**Pull request by jeevan-jp**
while loop has been used to improve delay function

### CODE REVIEW

**Comment by jeevan-jp** [comment]
fixes #585

**Comment by lpinca** [comment]
This is very wrong as it blocks the event loop. Run this

```
const promise = new Promise(function (resolve) {
  const now = new Date().getTime();
  while (new Date().getTime() < now + 5000) {
    /* Do nothing */
  }
  resolve(null);
});

console.log('OK');
```

and note how "OK" is printed _after_ 5 seconds. It should be printed immediately.

**Comment by jeevan-jp** [comment]
Yeah, just went through this repo's delay function calls. You are right, blocking main thread would affect further processing by caller function.

I am still wondering whether there is a better implementation, since accuracy is something that's not guaranteed with setTimeout.

Seems there is none.

**Comment by lpinca** [comment]
> I am still wondering whether there is a better implementation, since accuracy is something that's not guaranteed with setTimeout.

It is a very small inaccuracy (few milliseconds at most) so I think it does not matter.

**Comment by lpinca** [comment]
I'm closing this. Thank you anyway.

**Pull request closed without merging**
