### PR TITLE
Update customer.js - method orders to allow params in request

### PR DESCRIPTION
**Pull request by a-zharkov**
In case if we need to get any customer orders, then we need to pass parameter `status=any` to this request.
Thank you.

### CODE REVIEW

**Comment by lpinca** [comment]
This isn't documented, can you please add a test?
It's ok to just copy https://github.com/MONEI/Shopify-api-node/blob/b2a9adce3654d834e452545e937b6dfba4b8c8ed/test/customer.test.js#L149-L158

and add a dummy query parameter like it's done here https://github.com/MONEI/Shopify-api-node/blob/b2a9adce3654d834e452545e937b6dfba4b8c8ed/test/customer.test.js#L64

Thank you.

**Comment by a-zharkov** [comment]
Yes, sure, will do now. Shopify don't document a lot of things :)

**Comment by lpinca** [comment]
Would you mind fixing the lint issue?

**Comment by a-zharkov** [comment]
I used github editor, okay let me check in IDE.

**Comment by a-zharkov** [comment]
@lpinca Done. Could you please advise when the next release will be, because we need this fix in our project in the code that already on production. So asap release will be very helpful. Thank you!

**Comment by lpinca** [comment]
I'll merge this and cut a new release later today.

**Comment by lpinca** [comment]
Thank you.

**Pull request merged**
