### PR TITLE
Add batch to create a discount code creation job

### PR DESCRIPTION
**Pull request by baorv**

### CODE REVIEW

**Comment by lpinca** [comment]
Is there any official documentation for this? I can't find it here https://help.shopify.com/en/api/reference/discounts/pricerule.

**Comment by baorv** [comment]
It is located here
https://help.shopify.com/en/api/reference/discounts/discountcode#batch_create-2019-10

**Comment by lpinca** [comment]
It should be on DiscountCode then not on PriceRule. Also please add documentation and tests.

**Comment by baorv** [comment]
I moved it to DiscountCode, add documentation and tests.

**Comment by lpinca** [comment]
Thank you @baorv but I'm closing in favor of https://github.com/MONEI/Shopify-api-node/pull/318 as I noticed there is also https://help.shopify.com/en/api/reference/discounts/discountcode?api[version]=2019-10#batch_show-2019-10 and https://help.shopify.com/en/api/reference/discounts/discountcode?api[version]=2019-10#batch_discount_codes_index-2019-10.

**Comment by baorv** [comment]
Thank you. It is awesome, but you forgot to publish this version.

**Comment by lpinca** [comment]
I did not forget I'll merge this https://github.com/MONEI/Shopify-api-node/pull/319 and cut a new version later today.

**Comment by baorv** [comment]
I checked it on npmjs.com. It still 2.24.0 and the last version is released 11 days ago.

**Comment by lpinca** [comment]
Yes, I'll cut a new version later today.

**Comment by lpinca** [comment]
Done, I've just published `shopify-api-node@2.25.0`.

**Comment by baorv** [comment]
@lpinca Thank you! It's awesome!

**Pull request closed without merging**
