### PR TITLE
added count params to types

### PR DESCRIPTION
**Pull request by jared-fraser**
Types definition is missing params available to the customer count request.

### CODE REVIEW

**Comment by lpinca** [comment]
It does not take any parameter https://help.shopify.com/en/api/reference/customers/customer#count. Am I missing something?

**Comment by lpinca** [comment]
Can you also update the README accordingly? Thank you.

**Comment by jared-fraser** [comment]
Thanks @lpinca, it's an undocumented feature I guess. I have updated the README

You definitely can pass in the follow params and those will change count returned. Its how I do pagination for syncing customers on some of my stores.

ids | Restrict results to customers specified by a comma-separated list of IDs.
-- | --
since_id | Restrict results to those after the specified ID.
created_at_min | Show customers created after a specified date.(format: 2014-04-25T16:15:47-04:00)
created_at_max | Show customers created before a specified date.(format: 2014-04-25T16:15:47-04:00)
updated_at_min | Show customers last updated after a specified date.(format: 2014-04-25T16:15:47-04:00)
updated_at_max | Show customers last updated before a specified date.(format: 2014-04-25T16:15:47-04:00)

**Comment by lpinca** [comment]
Thank you.

**Pull request merged**
